name: Quality + Docker Deploy Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CUBE }}

  docker-build-push:
    needs: build-quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub (CLI)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.prod -t amanverma26/testing:latest .
          docker tag amanverma26/testing:latest amanverma26/testing:${{ github.sha }}

      - name: Push Docker Images
        run: |
          docker push amanverma26/testing:latest
          docker push amanverma26/testing:${{ github.sha }}